services:
  nginx:
    image: thenoosh/sna-nx-img:latest
    container_name: sna-ncon
    networks:
      - sna-nw-b
    ports: 
      - "80:80"
    depends_on:
      - frontend

  frontend:
    image: thenoosh/sna-fend-img:latest
    container_name: sna-fcon
    networks: 
      - sna-nw-b
    depends_on: 
      - backend

  backend:
    image: thenoosh/sna-bend-img:latest
    container_name: sna-bcon
    networks: 
      - sna-nw-b
    env_file:
      - .env
    depends_on:
      - mongodb
    
  mongodb:
    image: mongo:8.2
    container_name: sna-mcon
    networks:
      - sna-nw-b
    volumes:
      - sna-data:/data/db 
    env_file:
      - .env


networks:
  sna-nw-b:

volumes:
  sna-data:
