name: build and push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildnpush:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker Images
        run: docker build -t sna-fend-img:latest ./frontend
